<!DOCTYPE html>
<html lang="en">
<?php include('includes/head.php'); ?>
<body>
    <div id="wrapper">
        <?php include('includes/top-nav-bar.php'); ?>
        <?php include('includes/sidebar.php'); ?>

        <div class="content-page">
            <div class="content">
                <div class="container-fluid">
                    <div class="row mt-3">
                        <div class="col-12">
                            <?php if ($this->session->flashdata('msg')): ?>
                                <?= $this->session->flashdata('msg'); ?>
                            <?php endif; ?>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title mb-3">Add Branch / Cost Center</h4>
                                    <form method="post">
                                        <div class="form-group">
                                            <label>Code</label>
                                            <input type="text" name="DeptCode" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="text" name="DeptName" class="form-control" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Location / Area (optional)</label>
                                            <input type="text" name="Location" class="form-control" placeholder="e.g., Davao, Online">
                                        </div>
                                        <div class="form-group">
                                            <label>Notes (optional)</label>
                                            <input type="text" name="Notes" class="form-control" placeholder="any short note">
                                        </div>
                                        <div class="form-group">
                                            <label>Activation Key</label>
                                            <input type="text" name="activation_key" class="form-control" placeholder="BR-XXXX-XXXX-XXXX" required>
                                            <small class="form-text text-muted">A branch key generated by the System Administrator is required for each new branch.</small>
                                        </div>
                                        <button type="submit" name="submit" class="btn btn-primary">Save</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title mb-3">Branches / Cost Centers</h4>
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Code</th>
                                                    <th>Name</th>
                                                    <th>Location / Area</th>
                                                    <th>Notes</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php if (!empty($data)): ?>
                                                    <?php foreach ($data as $row): ?>
                                                        <tr>
                                                            <td><?= htmlspecialchars($row->DeptCode ?? '', ENT_QUOTES, 'UTF-8'); ?></td>
                                                            <td><?= htmlspecialchars($row->DeptName ?? '', ENT_QUOTES, 'UTF-8'); ?></td>
                                                            <td><?= htmlspecialchars($row->Location ?? '', ENT_QUOTES, 'UTF-8'); ?></td>
                                                            <td><?= htmlspecialchars($row->Notes ?? '', ENT_QUOTES, 'UTF-8'); ?></td>
                                                        </tr>
                                                    <?php endforeach; ?>
                                                <?php else: ?>
                                                    <tr><td colspan="4" class="text-center text-muted">No departments yet.</td></tr>
                                                <?php endif; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php include('includes/footer.php'); ?>
            </div>
        </div>
    </div>

    <?php include('includes/themecustomizer.php'); ?>
    <script src="<?= base_url(); ?>assets/js/vendor.min.js"></script>
    <script src="<?= base_url(); ?>assets/js/app.min.js"></script>
</body>
</html>
