CREATE TABLE IF NOT EXISTS `POS_products` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `settingsID` int unsigned NOT NULL DEFAULT 0,
  `sku` varchar(50) NOT NULL,
  `barcode` varchar(60) DEFAULT NULL,
  `name` varchar(150) NOT NULL,
  `category` varchar(80) DEFAULT NULL,
  `unit` varchar(20) DEFAULT 'pcs',
  `unit_cost` double NOT NULL DEFAULT 0,
  `unit_price` double NOT NULL DEFAULT 0,
  `stock_qty` int NOT NULL DEFAULT 0,
  `reorder_level` int NOT NULL DEFAULT 5,
  `tax_type` varchar(20) NOT NULL DEFAULT 'vatable',
  `discount_eligible` tinyint(1) NOT NULL DEFAULT 1,
  `expiry_date` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_products_settings` (`settingsID`),
  KEY `idx_pos_products_sku` (`sku`),
  KEY `idx_pos_products_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `pos_sales` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `settingsID` int unsigned NOT NULL,
  `sale_no` varchar(50) NOT NULL,
  `transaction_date` date NOT NULL,
  `transaction_time` time DEFAULT NULL,
  `terminal_no` varchar(50) DEFAULT NULL,
  `customer_id` varchar(50) DEFAULT NULL,
  `customer_name` varchar(150) NOT NULL DEFAULT 'Walk-in Customer',
  `customer_address` varchar(255) DEFAULT NULL,
  `customer_tin` varchar(50) DEFAULT NULL,
  `customer_discount_id` varchar(80) DEFAULT NULL,
  `customer_discount_type` varchar(20) NOT NULL DEFAULT 'none',
  `cashier_name` varchar(120) NOT NULL,
  `payment_term` varchar(20) NOT NULL DEFAULT 'full',
  `payment_mode` varchar(40) DEFAULT NULL,
  `subtotal` double NOT NULL DEFAULT 0,
  `discount_amount` double NOT NULL DEFAULT 0,
  `vatable_sales` double NOT NULL DEFAULT 0,
  `vat_exempt_sales` double NOT NULL DEFAULT 0,
  `zero_rated_sales` double NOT NULL DEFAULT 0,
  `vat_amount` double NOT NULL DEFAULT 0,
  `grand_total` double NOT NULL DEFAULT 0,
  `amount_paid` double NOT NULL DEFAULT 0,
  `balance_due` double NOT NULL DEFAULT 0,
  `change_amount` double NOT NULL DEFAULT 0,
  `installment_count` int unsigned NOT NULL DEFAULT 0,
  `installment_interval_days` int unsigned NOT NULL DEFAULT 0,
  `first_due_date` date DEFAULT NULL,
  `notes` text,
  `discount_label` varchar(100) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'Unpaid',
  `void_reason` varchar(255) DEFAULT NULL,
  `voided_by` varchar(120) DEFAULT NULL,
  `voided_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_sales_settings_date` (`settingsID`,`transaction_date`),
  KEY `idx_pos_sales_status` (`status`),
  KEY `idx_pos_sales_sale_no` (`sale_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `pos_sale_items` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` int unsigned NOT NULL,
  `settingsID` int unsigned NOT NULL,
  `product_id` int unsigned DEFAULT NULL,
  `sku` varchar(50) DEFAULT NULL,
  `product_name` varchar(150) NOT NULL,
  `category` varchar(80) DEFAULT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `tax_type` varchar(20) NOT NULL DEFAULT 'vatable',
  `discount_eligible` tinyint(1) NOT NULL DEFAULT 1,
  `quantity` int unsigned NOT NULL DEFAULT 1,
  `unit_cost` double NOT NULL DEFAULT 0,
  `unit_price` double NOT NULL DEFAULT 0,
  `line_subtotal` double NOT NULL DEFAULT 0,
  `line_discount` double NOT NULL DEFAULT 0,
  `line_vatable_sales` double NOT NULL DEFAULT 0,
  `line_vat_exempt_sales` double NOT NULL DEFAULT 0,
  `line_zero_rated_sales` double NOT NULL DEFAULT 0,
  `line_vat_amount` double NOT NULL DEFAULT 0,
  `line_total` double NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_sale_items_sale` (`sale_id`,`settingsID`),
  KEY `idx_pos_sale_items_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `pos_payments` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` int unsigned NOT NULL,
  `settingsID` int unsigned NOT NULL,
  `payment_date` date NOT NULL,
  `payment_time` time DEFAULT NULL,
  `amount` double NOT NULL DEFAULT 0,
  `payment_mode` varchar(40) DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `received_by` varchar(120) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `is_initial` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_payments_sale` (`sale_id`,`settingsID`),
  KEY `idx_pos_payments_date` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `pos_installment_schedule` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `sale_id` int unsigned NOT NULL,
  `settingsID` int unsigned NOT NULL,
  `installment_no` int unsigned NOT NULL DEFAULT 1,
  `due_date` date NOT NULL,
  `amount_due` double NOT NULL DEFAULT 0,
  `amount_paid` double NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'Unpaid',
  `paid_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_installments_sale` (`sale_id`,`settingsID`),
  KEY `idx_pos_installments_due` (`due_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `pos_inventory_movements` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `settingsID` int unsigned NOT NULL,
  `product_id` int unsigned NOT NULL,
  `sale_id` int unsigned DEFAULT NULL,
  `movement_type` varchar(30) NOT NULL,
  `quantity_change` int NOT NULL DEFAULT 0,
  `qty_before` int NOT NULL DEFAULT 0,
  `qty_after` int NOT NULL DEFAULT 0,
  `remarks` varchar(255) DEFAULT NULL,
  `created_by` varchar(120) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pos_movements_product` (`product_id`,`settingsID`),
  KEY `idx_pos_movements_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
